name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Replace Secrets
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          if [ -z "$BOT_TOKEN" ]; then
            echo "❌ ERROR: TELEGRAM_BOT_TOKEN is empty! Check your GitHub Secrets."
            exit 1
          fi
          sed -i "s/__BOT_TOKEN_PLACEHOLDER__/$BOT_TOKEN/g" script.js
          sed -i "s/__ADMIN_CHAT_ID_PLACEHOLDER__/$CHAT_ID/g" script.js
          echo "✅ Secrets replaced successfully."

      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
